name: Generate Snake Animation

on:
  # Ejecutar diariamente a medianoche UTC
  schedule:
    - cron: "0 0 * * *"

  # Permitir ejecución manual
  workflow_dispatch:

  # Ejecutar al hacer push en main
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # 1. Clonar el repositorio
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Generar las animaciones de la serpiente
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3. Hacer deploy al branch 'output' usando un token personal
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation [skip ci]"
